#ifndef RIFT_CORE_H
#define RIFT_CORE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define RIFT_MAJOR_VERSION "0"
#define RIFT_MINOR_VERSION "0"
#define RIFT_PATCH_VERSION "1"
#define RIFT_VERSION_EXTRA "-dev"

#define RIFT_VERSION_FULL "0.0.1-dev"

#define UNUSED(__X__) (void) __X__

#define MAX_ERROR_LEN 256

#define ERROR_RESULT            \
do {                            \
char buf[MAX_ERROR_LEN];        \
getStrerror(buf, errno);        \
return newResultError(vm, buf); \
} while false;

#ifndef PATH_MAX
#define PATH_MAX 4096
#endif

#ifdef _WIN32
#define DIR_SEPARATOR '\\'
#define DIR_ALT_SEPARATOR '/'
#define DIR_SEPARATOR_AS_STRING "\\"
#define DIR_SEPARATOR_STRLEN 1
#define PATH_DELIMITER ';'
#define PATH_DELIMITER_AS_STRING ";"
#define PATH_DELIMITER_STRLEN 1
#else
#define HAS_REALPATH
#define DIR_SEPARATOR '/'
#define DIR_SEPARATOR_AS_STRING "/"
#define DIR_SEPARATOR_STRLEN 1
#define PATH_DELIMITER ':'
#define PATH_DELIMITER_AS_STRING ":"
#define PATH_DELIMITER_STRLEN 1
#endif

#ifdef DIR_ALT_SEPARATOR
#define IS_DIR_SEPARATOR(c) ((c) == DIR_SEPARATOR || (c) == DIR_ALT_SEPARATOR)
#else
#define IS_DIR_SEPARATOR(c) (c == DIR_SEPARATOR)
#endif

#define NAN_TAGGING
#define DEBUG_PRINT_CODE
#define DEBUG_TRACE_EXECUTION
#define DEBUG_TRAGE_GC
#define DEBUG_TRACE_MEM

#ifndef _MSC_VER
#define COMPUTED_GOTO
#endif

#undef DEBUG_PRINT_CODE
#undef DEBUG_TRACE_EXECUTION
#undef DEBUG_TRACE_GC
#undef DEBUG_TRACE_MEM

#define UINT8_COUNT (UINT8_MAX + 1)

typedef struct _vm RiftVM;

typedef enum {
    INTERPRET_OK,
    INTERPRET_COMPILE_ERROR,
    INTERPRET_RUNTIME_ERROR
} RiftInterpretResult;

RiftVM *riftInitVM(bool repl, int argc, char *argv[]);
void riftFreeVM(RiftVM *vm);

RiftInterpretResult riftInterpret(RiftVM *vm, char *moduleName, char *source);

/** Opcodes in here */
OPCODE(CONSTANT)
OPCODE(NIL)
OPCODE(TRUE)
OPCODE(FALSE)
OPCODE(NEW_LIST)
OPCODE(UNPACK_LIST)
OPCODE(NEW_DICT)
OPCODE(SUBSCRIPT)
OPCODE(SUBSCRIPT_ASSIGN)
OPCODE(SUBSCRIPT_PUSH)
OPCODE(SLICE)
OPCODE(POP)
OPCODE(GET_LOCAL)
OPCODE(SET_LOCAL)
OPCODE(GET_GLOBAL)
OPCODE(GET_MODULE)
OPCODE(DEFINE_MODULE)
OPCODE(DEFINE_OPTIONAL)
OPCODE(SET_MODULE)
OPCODE(GET_UPVALUE)
OPCODE(SET_UPVALUE)
OPCODE(GET_PROPERTY)
OPCODE(GET_PROPERTY_NO_POP)
OPCODE(SET_PROPERTY)
OPCODE(SET_CLASS_VAR)
OPCODE(SET_INIT_PROPERTIES)
OPCODE(GET_SUPER)
OPCODE(EQUAL)
OPCODE(GREATER)
OPCODE(LESS)
OPCODE(ADD)
OPCODE(SUBTRACT)
OPCODE(MULTIPLY)
OPCODE(DIVIDE)
OPCODE(POW)
OPCODE(MOD)
OPCODE(NOT)
OPCODE(NEGATE)
OPCODE(JUMP)
OPCODE(JUMP_IF_FALSE)
OPCODE(JUMP_IF_NIL)
OPCODE(LOOP)
OPCODE(CALL)
OPCODE(INVOKE)
OPCODE(SUPER)
OPCODE(CLOSURE)
OPCODE(CLOSE_UPVALUE)
OPCODE(RETURN)
OPCODE(EMPTY)
OPCODE(CLASS)
OPCODE(SUBCLASS)
OPCODE(END_CLASS)
OPCODE(METHOD)
OPCODE(IMPORT)
OPCODE(IMPORT_BUILTIN)
OPCODE(IMPORT_BUILTIN_VARIABLE)
OPCODE(IMPORT_VARIABLE)
OPCODE(IMPORT_FROM)
OPCODE(IMPORT_END)
OPCODE(USE)
OPCODE(OPEN_FILE)
OPCODE(BREAK)
OPCODE(CLOSE_FILE)
OPCODE(BITWISE_AND)
OPCODE(BITWISE_XOR)
OPCODE(BITWISE_OR)
OPCODE(POP_REPL)

#endif /** End RIFT_COMMON_H */
